version: "3.8"
services:
  api:
    container_name: "api"
    build:
      context: .
      dockerfile: Dockerfile.air
    ports:
      - "8080:8080"
    links:
      - mongo
    volumes:
      - ./:/app
  mongo:
    container_name: "mongo"
    image: mongo
    ports:
      - "27017:27017"
